# Generated by Django 3.0.8 on 2021-01-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogotaSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('cedula', models.BigIntegerField(blank=True, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bogota_sms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'codigos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipificaciones',
            fields=[
                ('codigo01', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo02', models.IntegerField()),
                ('codigo03', models.IntegerField()),
                ('codigo04', models.IntegerField()),
                ('codigo05', models.IntegerField()),
                ('codigo06', models.IntegerField()),
                ('codigo07', models.IntegerField()),
                ('codigo08', models.IntegerField()),
                ('codigo09', models.IntegerField()),
                ('codigo10', models.IntegerField()),
                ('prioridad', models.IntegerField()),
                ('indicador', models.IntegerField()),
            ],
            options={
                'db_table': 'tipificaciones',
                'managed': False,
            },
        ),
    ]
