# Generated by Django 3.0.8 on 2021-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreRama',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nombre_rama',
                'managed': False,
            },
        ),
    ]
