# Generated by Django 3.0.8 on 2021-01-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_nombrerama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('gestion_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tarea_id', models.BigIntegerField()),
                ('gestion_fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.CharField(max_length=50)),
                ('deudor_id', models.CharField(max_length=100)),
                ('asignacion_id', models.BigIntegerField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('canal', models.CharField(max_length=20)),
                ('tipificacion', models.CharField(max_length=100)),
                ('codigo01', models.IntegerField(blank=True, null=True)),
                ('codigo02', models.IntegerField(blank=True, null=True)),
                ('codigo03', models.IntegerField(blank=True, null=True)),
                ('codigo04', models.IntegerField(blank=True, null=True)),
                ('codigo05', models.IntegerField(blank=True, null=True)),
                ('codigo06', models.IntegerField(blank=True, null=True)),
                ('codigo07', models.IntegerField(blank=True, null=True)),
                ('codigo08', models.IntegerField(blank=True, null=True)),
                ('codigo09', models.IntegerField(blank=True, null=True)),
                ('codigo10', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nom_contacto_tercero', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_adicional', models.BigIntegerField(blank=True, null=True)),
                ('ciudad_tel_adicional', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'gestiones',
                'managed': False,
            },
        ),
    ]
