# Generated by Django 3.0.8 on 2021-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_gestiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tarea_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tarea_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('unidad_id', models.BigIntegerField()),
                ('registros', models.BigIntegerField()),
                ('clientes', models.BigIntegerField()),
                ('obligaciones', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
    ]
