# Generated by Django 3.0.8 on 2021-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('asignacion_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asignacion_nombre', models.CharField(max_length=100)),
                ('asignacion_fecha_creacion', models.DateField()),
                ('clientes', models.BigIntegerField()),
                ('obligaciones', models.BigIntegerField()),
                ('estado', models.BooleanField()),
                ('fecha_apertura', models.DateField()),
            ],
            options={
                'db_table': 'asignaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('unidad_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unidad_nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('unidad_estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
    ]
