# Generated by Django 3.0.8 on 2021-01-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_asignaciones_unidades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BogotaSms',
        ),
    ]
