# Generated by Django 3.0.8 on 2021-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VicidialStatusValidator',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('call_type', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'vicidial_status_validator',
                'managed': False,
            },
        ),
    ]
